flags: {}
resolver: lts-12.12
extra-deps:
- fltkhs-0.6.0.0
- fltkhs-themes-0.1.0.0
- load-font-0.1.0.2
- asset-bundle-0.1.0.1

nix:
  enable: true
  packages:
  - fontconfig
  - pkgconfig
  - autoconf
  - unzip
  - x11
  - xorg.libX11
  - xorg.libXext
  - xorg.libXinerama
  - xorg.libXrandr
  - xorg.libXrender
  - zip
